workflows:
  ios_app_store:
    name: iOS App Store Build
    max_build_duration: 60
    environment:
      vars:
        APP_IDENTIFIER: com.kalimba.airec
        APP_NAME: Kalimba
        XCODE_WORKSPACE: App.xcworkspace
        XCODE_SCHEME: App
      groups:
        - app_store_connect

    scripts:
      - name: Install dependencies
        script: |
          npm ci
          npx cap sync ios
          cd ios/App
          pod install

      - name: Archive Xcode project
        script: |
          cd ios/App
          xcodebuild -workspace $XCODE_WORKSPACE \
            -scheme $XCODE_SCHEME \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/App.xcarchive archive

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            -exportOptionsPlist $CM_SOURCE_DIR/ExportOptions.plist \
            -exportPath $CM_BUILD_DIR/build

    artifacts:
      - build/*.ipa
      - $CM_BUILD_DIR/**/Logs/*.log

    publishing:
      app_store_connect:
        api_key: $ASC_KEY
        key_id: $ASC_KEY_ID
        issuer_id: $ASC_ISSUER_ID
        team_id: $APPLE_TEAM_ID
        submit_to_testflight: true
